const ARTIST_SET_DATA = 'ARTIST_SET_DATA'
const ARTIST_SET_LOADING = 'ARTIST_SET_LOADING'
const ARTIST_SET_ERROR = 'ARTIST_SET_ERROR';

export {
    ARTIST_SET_DATA,
    ARTIST_SET_ERROR,
    ARTIST_SET_LOADING
}