const SEARCH_TRACKS_SET_DATA = 'SEARCH_TRACKS_SET_DATA';
const SEARCH_TRACKS_SET_LOADING = 'SEARCH_TRACKS_SET_LOADING';
const SEARCH_TRACKS_SET_ERROR = 'SEARCH_TRACKS_SET_ERROR';
const SEARCH_TRACKS_SET_INPUT = 'SEARCH_TRACKS_SET_INPUT'

export {
    SEARCH_TRACKS_SET_DATA,
    SEARCH_TRACKS_SET_ERROR,
    SEARCH_TRACKS_SET_LOADING,
    SEARCH_TRACKS_SET_INPUT,
}