const TOP_TRACKS_SET_DATA = 'TOP_TRACKS_SET_DATA';
const TOP_TRACKS_SET_LOADING = 'TOP_TRACKS_SET_LOADING';
const TOP_TRACKS_SET_ERROR = 'TOP_TRACKS_SET_ERROR';

export {
    TOP_TRACKS_SET_DATA,
    TOP_TRACKS_SET_ERROR,
    TOP_TRACKS_SET_LOADING,
}